nqubits: 8
description: Eight qubit 2D structure

settings:
    nshots: 1000
    relaxation_time: 150_000

qubits: [0, 1, 2, 3, 4, 5, 6, 7]

topology: [[5, 6]]

native_gates:
    single_qubit: 
        0:
            MZ:
                duration: 5000
                amplitude: 1
                frequency: 4794814285.71
                shape: Rectangular()
                type: ro # readout
                relative_start: 0
                phase: 0
            RX:
                duration: 48
                amplitude: 0.1
                frequency: 3978886780.2930303
                shape: Drag(7, 0)
                type: qd # qubit drive
                relative_start: 0
                phase: 0
        2:
            MZ:
                duration: 5000
                amplitude: 1
                frequency: 5361642857.14
                shape: Rectangular()
                type: ro # readout
                relative_start: 0
                phase: 0
            RX:
                duration: 39
                amplitude: 0.4
                frequency: 4004035975.4358234
                shape: Drag(7, 0)
                type: qd # qubit drive
                relative_start: 0
                phase: 0
        4:
            MZ:
                duration: 5000
                amplitude: 1
                frequency: 5750081632.65
                shape: Rectangular()
                type: ro # readout
                relative_start: 0
                phase: 0
            RX:
                duration: 26
                amplitude: 0.2
                frequency: 3850224873.904726
                shape: Drag(7, 0)
                type: qd # qubit drive
                relative_start: 0
                phase: 0
        5:
            MZ:
                duration: 5000
                amplitude: 1
                frequency: 5549081632.65
                shape: Rectangular()
                type: ro # readout
                relative_start: 0
                phase: 0
            RX:
                duration: 40
                amplitude: 0.4
                frequency: 3786845470.823299
                shape: Drag(7, 0)
                type: qd # qubit drive
                relative_start: 0
                phase: 0
        6:
            MZ:
                duration: 5000
                amplitude: 1
                frequency: 5185830612.24
                shape: Rectangular()
                type: ro # readout
                relative_start: 0
                phase: 0
            RX:
                duration: 71
                amplitude: 0.9
                frequency: 3467710051.327039
                shape: Drag(7, 0)
                type: qd # qubit drive
                relative_start: 0
                phase: 0
        7:
            MZ:
                duration: 5000
                amplitude: 1
                frequency: 4944136363.64
                shape: Rectangular()
                type: ro # readout
                relative_start: 0
                phase: 0
            RX:
                duration: 58
                amplitude: 0.4
                frequency: 3545591851.55596
                shape: Drag(7, 0)
                type: qd # qubit drive
                relative_start: 0
                phase: 0

characterization:
    single_qubit:
        0: 
            T1: 4110
            T2: 2770
            anharmonicity: 178
        1: {}
        2:
            T1: 280
        3: 
            T1: 6790
            T2: 2069
            T2_spin_echo: 5260
            anharmonicity: 241
        4:
            T1: 4910
            T2_spin_echo: 5180
            T2: 2980
            anharmonicity: 236
        5:
            T1: 650
            T2_spin_echo: 220
            T2: 250
            anharmonicity: 202
        6:
            T1: 2560
            T2_spin_echo: 710
            T2: 710
            anharmonicity: 204
        7:
            T1: 10250
            T2_spin_echo: 10390
            T2: 4090
            anharmonicity: 252
